name: RSpec

on: [push, pull_request]

env:
  RUBY_VERSION: "2.7.3"

jobs:
  rspec:
    runs-on: ubuntu-latest
    container:
      image: ruby:${{ env.RUBY_VERSION }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: bundle install
        run: |
          gem install bundler
          bundle config --global set path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Run RSpec
        run: bundle exec rspec --format progress

  rubocop:
    runs-on: ubuntu-latest
    container:
      image: ruby:${{ env.RUBY_VERSION }}
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-ruby@v1
          with:
            ruby-version: ${{ env.RUBY_VERSION }}
        - name: bundle install
          run: |
            gem install bundler
            bundle config --global set path vendor/bundle
            bundle install --jobs 4 --retry 3
        - name: Run RSpec
          run: bundle exec rubocop
