# For all options see https://github.com/bbatsov/rubocop/tree/master/config

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Include:
    - Rakefile

GlobalVars:
  AllowedVariables: [$statsd]

Lint/UnneededDisable:
  Severity: error

Metrics/AbcSize:
  Max: 30

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Max: 90

# Avoid methods longer than 30 lines of code
Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 87

Metrics/BlockLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  CountKeywordArgs: false

# Allow non-ASCII characters (e.g. £) in comments
Style/AsciiComments:
  Enabled: false

Style/Alias:
  Enabled: true
  EnforcedStyle: prefer_alias_method

# Use trailing rather than leading dots on multi-line call chains
Layout/DotPosition:
  EnforcedStyle: trailing

Style/Documentation:
  Enabled: false

Style/FormatString:
  EnforcedStyle: sprintf

# As of 0.43.0 this cop complains in situations where a guard clause would be
# unhelpful or erroneous.
# The auto-correct is also buggy.
Style/GuardClause:
  Enabled: false

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/IndentHash:
  EnforcedStyle: consistent

Naming/FileName:
  Exclude:
    - Gemfile

Style/FrozenStringLiteralComment:
  Enabled: always

Style/Lambda:
  EnforcedStyle: literal

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/NumericPredicate:
  Exclude:
    - 'spec/**/*'

Style/NumericLiterals:
  MinDigits: 11

# As of 0.43.0 this cop has many false positives
# https://github.com/bbatsov/rubocop/pull/3517 may fix a lot of these
Style/SafeNavigation:
  Enabled: false

Style/SignalException:
  EnforcedStyle: 'only_raise'

# Wants you to use the same argument names for every reduce. This seems kinda
# naff compared to naming them semantically
Style/SingleLineBlockParams:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: 'double_quotes'

Naming/VariableNumber:
  Enabled: false

Rails:
  Enabled: false
