# For all options see https://github.com/bbatsov/rubocop/tree/master/config

AllCops:
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  NewCops: disable
  SuggestExtensions: false

Layout/LineLength:
  Max: 90

Metrics/AbcSize:
  Max: 30

Metrics/ClassLength:
  Enabled: false

# Avoid methods longer than 30 lines of code
Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 87

Metrics/BlockLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/CyclomaticComplexity:
  Max: 8

# Allow non-ASCII characters (e.g. £) in comments
Style/AsciiComments:
  Enabled: false

Style/Alias:
  Enabled: true
  EnforcedStyle: prefer_alias_method

# Use trailing rather than leading dots on multi-line call chains
Layout/DotPosition:
  EnforcedStyle: trailing

Style/Documentation:
  Enabled: false

Style/FormatString:
  EnforcedStyle: sprintf

# As of 0.43.0 this cop complains in situations where a guard clause would be
# unhelpful or erroneous.
# The auto-correct is also buggy.
Style/GuardClause:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Naming/FileName:
  Exclude:
    - Gemfile

Style/FrozenStringLiteralComment:
  Enabled: true

Style/Lambda:
  EnforcedStyle: literal

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/ConstantDefinitionInBlock:
  Enabled: false

Style/NumericPredicate:
  Exclude:
    - 'spec/**/*'

Style/NumericLiterals:
  MinDigits: 11

# As of 0.43.0 this cop has many false positives
# https://github.com/bbatsov/rubocop/pull/3517 may fix a lot of these
Style/SafeNavigation:
  Enabled: false

Style/SignalException:
  EnforcedStyle: 'only_raise'

# Wants you to use the same argument names for every reduce. This seems kinda
# naff compared to naming them semantically
Style/SingleLineBlockParams:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: 'double_quotes'

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Naming/VariableNumber:
  Enabled: false



Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/DuplicateRescueException:
  Enabled: true

Lint/EmptyConditionalBody:
  Enabled: true

Lint/FloatComparison:
  Enabled: true

Lint/MissingSuper:
  Enabled: true

Lint/OutOfRangeRegexpRef:
  Enabled: true

Lint/SelfAssignment:
  Enabled: true

Lint/TopLevelReturnWithArgument:
  Enabled: true

Lint/UnreachableLoop:
  Enabled: true

Style/AccessorGrouping:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/ExplicitBlockArgument:
  Enabled: true

Style/GlobalStdStream:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/OptionalBooleanParameter:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/SingleArgumentDig:
  Enabled: true

Style/StringConcatenation:
  Enabled: false
