version: 2

references:
  install_bundle: &install_bundle
    run:
      name: Bundle
      command: gem install bundler && bundle install --path vendor/bundle --jobs=4 --retry=3

  restore_bundle_cache: &restore_bundle_cache
    restore_cache:
      key: discordtfl-{{ checksum "Gemfile.lock" }}

  save_bundle_cache: &save_bundle_cache
    save_cache:
      key: discordtfl-{{ checksum "Gemfile.lock" }}
      paths:
        - vendor/bundle

jobs:
  code_quality:
    docker:
      - image: circleci/ruby:2.5.3
    steps:
      - checkout
      - *restore_bundle_cache
      - *install_bundle
      - *save_bundle_cache
      - run:
          name: Rubocop
          command: bundle exec rubocop

  tests:
    docker:
      - image: circleci/ruby:2.5.3
    steps:
      - checkout
      - *restore_bundle_cache
      - *install_bundle
      - *save_bundle_cache
      - run:
          name: RSpec
          command: bundle exec rspec --format progress --format RspecJunitFormatter -o tmp/rspec-reports/unit.xml $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

workflows:
  version: 2
  tests:
    jobs:
      - code_quality
      - tests
