name: RSpec

on: [push, pull_request]

env:
  RUBY_VERSION: "2.7"

jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-${{ env.RUBY_VERSION }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.RUBY_VERSION }}-gems-
      - name: bundle install
        run: |
          gem install bundler
          bundle config --global set path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Run RSpec
        run: bundle exec rspec --format progress

  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-${{ env.RUBY_VERSION }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.RUBY_VERSION }}-gems-
      - name: bundle install
        run: |
          gem install bundler
          bundle config --global set path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Run RSpec
        run: bundle exec rubocop
